---
- hosts: localhost
  tasks:
    - include_vars: "{{ansible_os_family}}.yml"
  #  - include_vars: "Debian.yml"
    - include: install-debian.yml
      when: ansible_os_family == 'Debian'

    - include: install-redhat.yml
      when: ansible_os_family == 'RedHat'