
route:
  # If an alert does not match any rule, it goes to the default:
  receiver: slack_default
  routes:
    - match:
        severity: critical
      receiver: slack_alert
    - match:
        severity: warning
      receiver: slack_warning
receivers:
  - name: slack_alert
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/xxxxxx'
        text: "{{ .CommonAnnotations.description }}"
        username: ''your_name
        channel: '#critical_alerts'
  - name: slack_warning
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/xxx/xxx'
        text: "{{ .CommonAnnotations.description }}"
        username: 'your_name'
        channel: '#warning_alert'
  - name: slack_default
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/xxx/xxx'
        text: "{{ .CommonAnnotations.description }}"
        username: 'your_name'
        channel: '#prometheus'