---
- name: Delete All AWS resources
  hosts: all
  connection: local
  gather_facts: False
  tasks:
          - ec2_instance_facts:
                  region: eu-central-1
                  filters:
                          "tag:Name=Demo"
            register: instance_list
          - set_fact:
                  instance_ids: "{{instance_list.instances|map(attribute='instance_id')|list}}"
          - debug: var=instance_ids
          - ec2:
              region: ap-southeast-1
              instance_ids: "{{instance_ids}}"
              state: absent
