apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker-9001
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: worker-9001
  endpoints:
    - port: web
      path: actuator/prometheus
      interval: 30s