apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
    - image: busybox:1.30.1
      name: busybox
      args:
        - sleep
        - "3600"
      env:
        - name : PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password
