---

- hosts: webservers
  become: yes
  vars:
    http_port: 80
    doc_dir: /ansible/
    doc_root: /var/www/html/
    max_clients: 5

  vars_prompt:
    - name: username
      prompt: What is yoour name ? our quest? your favortie color ? 

  tasks:
  - name: ensure apache is installed
    apt: name=apache2 state=latest
    when: ansible_os_family == "Debian"

  - name: start apache service
    service: name=apache2 state=started

  - name: Deploy configuration file
    template: src=templates/httpd.j2 dest=/etc/apache2/apache2.conf
    when: ansible_os_family == "RedHat"
    notify:
      - Restart Apache

  - name: Copy site Files
    template: src=templates/index.j2 dest={{ doc_root }}/index.html
   
  handlers:
    - name: Restart Apache
      service: name=apache2 state=restarted

- hosts: dbservers
  become: yes

  tasks:
  - name: ensure mysql is installed
    apt: 
      pkg:
        - mysql-server-5.7
        - mysql-client-5.7
        - python-mysqldb
        - libmysqlclient-dev
      state: present 
    
 

