apiVersion: v1
kind: Pod
metadata:
  name: worker-9001
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9001'
    prometheus.io/path: '/actuator/prometheus'
spec:
  containers:
    - name: worker-9001
      image: 775884380616.dkr.ecr.eu-central-1.amazonaws.com/kube:latest
      ports:
        - containerPort: 9001
