apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  volumes:
    - name: v1
      persistentVolumeClaim:
        claimName: mypvc
  containers:
    - image: busybox
      name: pod1
      args:
        - /bin/sh
        - -c
        - sleep 2000
      volumeMounts:
        - name: v1
          mountPath: /etc/foo