---
- hosts: aws-ubuntu2
  gather_facts: true
  become: true
  vars:
    - database_name: michaelwp
    - database_user: michaelwp
    - database_password: bananas18374
    - wp_domain: book.example.com
  roles:
    - mheap.common
    - mheap.php
    - mheap.nginx
    - mheap.mysql
    - mheap.wordpress
