---
- hosts: aws-ubuntu2
  gather_facts:
  become: true
  roles:
    - role: mheap.wordpress
      database_name: michaelwp
      database_user: michaelwp
      database_password: bananas18374
      wp_domain: book.example.com