apiVersion: v1
kind: Pod
metadata:
  name: db
spec:
  containers:
    - image: mongo:4.0.6
      name: mongodb
      volumeMouns:
        - name: config
          mountPath: /config
      ports:
        - containerPort: 27017
          protocol: TCP
      volumes:
      - name: config
        configMap:
          name: app-config