---
- name: Ensure the HTTPd package is installed on DEbian
  apt:
    name: apache2
    state: present
  become: True

#- name: Ensure the HTTPd service is enabled and running
#  service:
#    name: apache2
#    state: started
#    enabled: True
#  become: True

- name: remove default config
  file:
    path: /etc/apache2/sites-available/000-default.conf
    state: absent
  become: true

- name: Ensure HTTPd configuration is updated
  template:
    src: website.conf
    dest: /etc/apache2/sites-available/000-default.conf
  become: True
  notify: Restart HTTPd

- name: Ensure the website is present and updated
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  become: True

