---
- hosts: all
  become: true
  tasks:
    - name: ensure ansible user exists
      user:
        name: ansible
        state: present
        comment: Ansible

    - name: Ensure ansible user accepts the SSH key
      authorized_key:
        user: ansible
        key: https://github.com/fale.keys
        state: present
    - name: Ensure the ansible user is sudoer with no password requires
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^ansible ALL\='
        line: 'ansible ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'