---
- name: ensure apache is installed
  apt: name=apache2 state=present

- name: start Apache
  service: name=apache2 state=started

#-name: deploy config

- name: Copy site Files
  template: src=templates/index.j2 dest={{ doc_root }}/index.html