apiVersion: v1
kind: Pod
metadata:
  labels:
    run: logs
  name: pod-logs
spec:
  containers:
    - image: busybox:1.30.1
      name: server
      ports:
        - containerPort: 8888
      command: ["/bin/sh","-c"]
      args: ["nc -p 8888 -v -lke echo Received request"]
      readinessProbe:
        tcpSocket:
          port: 8888
    - image: busybox:1.30.1
      name: client
      command: ["/bin/sh","-c"]
      args: ["while true;do sleep 5;nc localhost 8888; done"]

