apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-http
spec:
  containers:
    - image:httpd:2.4.38-alpine
      name: readiness
      ports:
        - containerPort: 80
      command: ["/bin/sh","-c"]
      args: ["sleep 30 && httpd-foreground"]
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3