apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-tcp
spec:
  containers:
    - image: busybox:1.30.1
      name: liveness
      ports:
        - containerPort: 8888
      command: ["/bin/sh","-c"]
      args: ["sleep 30 nc -p 8888 -lke echo hi && sleep 600"]
      liveessProbe:
        tcpsocket:
          port: 8888
        initialDelaySeconds: 3
        periodSeconds: 5
