apiVersion: v1
kind: Pod
metadata:
  name: load-limited
spec:
  containers:
    - name: cpu-load-limited
      image: vish/stress
      args:
        - -cpus
        - "2"
      resources:
        limits:
          cpu: "0.5"
          memory: "20Mi"
        requests:
          cpu: "0.25"
