apiVersion: batch/v1
kind: Job
metadata:
  name: pod-fail
spec:
  backoffLimit: 3
  completions: 6
  parallelism: 2
  template:
    spec:
      containers:
        - command: ['sleep 20 && exit 1']
          image: alpine
          name: fail
      restartPolicy: Never
