apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: ngnix-world
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30001
      protocol: TCP
  selector:
    run: nginx